require('../schema.js')
module.exports=function(req,res) {
	var obj=req.body;
	console.log(obj)
	user.findOne({username:obj.username},{_id:1,password:1,reportingManager:1},function(err,result){
		if(err)
			{
					res.json({
						status:"failure",
						err:err,
						data:null
					})
					console.log(err)
			}
		else
		{
			if(result)
			{
				if(result.password==obj.password)
				{
					res.json({
						status:"success",
						err:null,
						data:{
							uniqueid:result._id,
							reportingManager:result.reportingManager
						}
					})
				}
				else
				{
					res.json({
						status:"failure",
						err:"Invalid username or password",
						data:null
					})
				}
			}
			else
			{
				res.json({
					status:"failure",
					err:"Invalid username or password",
					data:null
				})
			}
		}
	})
}
